# 使用 Node.js 镜像作为基础镜像
FROM node:18.18.2

# 设置工作目录
WORKDIR /app

# 复制依赖文件并安装依赖
COPY package*.json ./

# 使用淘宝的 npm 镜像源
RUN npm config set registry https://registry.npmmirror.com/ && \
    npm install

# 复制源代码
COPY . .

# 生成 Prisma 客户端
RUN npx prisma generate

# 安装 Python 和 pip，并创建虚拟环境
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    python3 -m venv venv && \
    . venv/bin/activate && \
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install -r requirements.txt

# 暴露后端 API 服务端口
EXPOSE 5000
